/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package org.selenide.examples.scala2

import java.time.LocalDate
import java.time.temporal.ChronoUnit

class Person(private val birthDate: LocalDate) {
  def this() = {
    this(LocalDate.of(1970, 1, 1))
  }

  def age(): Int = ChronoUnit.YEARS.between(birthDate, today()).toInt
  
  def today(): LocalDate = LocalDate.now()
}
